### ISSUE TITLE
为什么getfilelist接口的hash值如此奇怪?

### ISSUE THREAD

**Issue by pythonwood** [ucloud/ufile-sdk-python#12]
{'BucketName': 'xxx',
              'CreateTime': 1595423492,
              'FileName': 'dev/xxx/path/504c1948ee7a8098a4ace',
              'Hash': 'AQAAAMpQBRvffOHgFJKDrRIQM2O9QTZe@session_61211181-cef1-429d-91d2-cf541d93de33',
              'MimeType': 'application/unknowntype',
              'ModifyTime': 1595423492,
              'Size': 27477,
              'StorageClass': 'STANDARD',
              'first_object': '61211181-cef1-429d-94d2-cf541d23xxx2e'}

这样的hash是为了好玩？just for fun ？
 'Hash': 'AQAAAMxxxxxxxxFJKDrRIQM2O9QTZe@session_61xxxx81-cef1-429d-94d2-cfxxxde2e',

**Comment by NightRain233** [comment]
该接口返回的Hash值由ETag和sessionid组成，session之前的为ETag，具体算法的伪代码如下: 
```
if filesize<=4MB:
    hash = base64_url_safe(blkcnt, sha(file))
else:
    hash = base64_url_safe(blkcnt, sha(sha(blk0), sha(blk1)...))
字段含义
    blkcnt:文件以4MB为一个块进行切分后的块个数。
    blkN:第N(N>=0)个数据块的数据。
```


 python-sdk计算ETag的代码在[ file_etag](https://github.com/ucloud/ufile-sdk-python/blob/5619eb2d1e9ac663bac4d095844c29a2c72c1028/ufile/util.py#L85)

@session开始的为sessionid，利用uuid v4计算得到。当前sessionid确实没有存在的实际意义，但是从兼容性的角度出发目前还是保留这样的方式。
