### ISSUE TITLE
有办法获取ufile上面的文件的文件url地址给前端展示吗

### ISSUE THREAD

**Issue by CheungChan** [ucloud/ufile-sdk-python#18]
如题

**Comment by NightRain233** [comment]
获取url可使用public_download_url或private_download_url
 
示例：
 
public_key = ''      #账户公钥
private_key = ''     #账户私钥
 
bucket = ''          #添加空间名称
put_key = ''         #文件名
host = ''            #bucket所在region的域名，不填写则默认为北京。 上海二：'.cn-sh2.ufileos.com'
 
from ufile import filemanager
 
url_handler = filemanager.FileManager(public_key, private_key,download_suffix=host)
url = url_handler.public_download_url(bucket,put_key)     #获得公有空间文件的url
url = url_handler.private_download_url(bucket,put_key)    #获得私有空间文件的url

**Comment by CheungChan** [comment]
> 获取url可使用public_download_url或private_download_url
> 
> 示例：
> 
> public_key = '' #账户公钥
> private_key = '' #账户私钥
> 
> bucket = '' #添加空间名称
> put_key = '' #文件名
> host = '' #bucket所在region的域名，不填写则默认为北京。 上海二：'.cn-sh2.ufileos.com'
> 
> from ufile import filemanager
> 
> url_handler = filemanager.FileManager(public_key, private_key,download_suffix=host)
> url = url_handler.public_download_url(bucket,put_key) #获得公有空间文件的url
> url = url_handler.private_download_url(bucket,put_key) #获得私有空间文件的url

问题已解决，非常感谢

**Comment by joydchh** [comment]
Mark as resolved.
