### ISSUE TITLE
Error occured when run  test demo.

### ISSUE THREAD

**Issue by flyingpang** [ucloud/ufile-sdk-python#7]
from ufile import filemanager
    putufile_handler = filemanager.FileManager(public_key, private_key)
    from io import BytesIO
    bio = BytesIO(u'Do be a good man'.encode('utf-8'))  #二进制数据流
    stream_key = 'test_test'                         #上传数据流在空间中的名称
    ret, resp = putufile_handler.putfile(public_bucket, stream_key, bio)
    print(resp)

`expected str, bytes or os.PathLike object, not _io.BytesIO` error was thrown

python3.7, ufile 3.1.0

**Comment by lizhenfu100** [comment]
which python version did you  used?

**Comment by flyingpang** [comment]
python 3.7.3

**Comment by lizhenfu100** [comment]
It should be `ret, resp = putufile_handler.putstream(public_bucket, stream_key, bio)`
We have fix our readme.Thanks for ur issue
